name: Deploy to QA and Production with Load Balancer

on:
  push:
    branches:
      - qa
      - production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        if [ "${{ github.ref_name }}" == "qa" ]; then
          TAG="qa"
        elif [ "${{ github.ref_name }}" == "production" ]; then
          TAG="prod"
        else
          echo "Branch not configured for deployment"
          exit 1
        fi

        docker build -t luna28kenya412/my-html-app .
        docker push luna28kenya412/my-html-app
    - name: Deploy Docker Image to EC2 Instances
      run: |
        if [ "${{ github.ref_name }}" == "qa" ]; then
          EC2_USER=${{ secrets.EC2_QA_USER }}
          EC2_HOST=${{ secrets.EC2_QA_HOST }}
          TAG="qa"
        elif [ "${{ github.ref_name }}" == "production" ]; then
          EC2_USER=${{ secrets.EC2_PROD_USER }}
          EC2_HOST=${{ secrets.EC2_PROD_HOST }}
          TAG="prod"
        else
          echo "Branch not configured for deployment"
          exit 1
        fi

        ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << EOF
        docker pull your-dockerhub-username/hello-world:$TAG
        docker stop hello-world || true
        docker rm hello-world || true
        docker run -d -p 80:80 --name hello-world your-dockerhub-username/hello-world:$TAG
        EOF
